# YAML anchors

_defaults:
  docker: &docker
    conditions:
      - "[STATUS] == 200"
      - "[BODY].State.Health.Status == healthy"
    ui:
      hide-hostname: true

# main config

storage:
  type: sqlite
  path: /data/data.db

web:
  port: ${PORT}

ui:
  title: "Gatus @ status.objectobject.ca"
  header: "status.objectobject.ca"
  description: "Gatus page for services hosted on objectobject.ca."
  buttons:
    - name: Dozzle
      link: https://status.objectobject.ca/dozzle
    - name: Source
      link: https://github.com/object-Object/objectobject.ca

endpoints:
  - name: discord-github-utils-api
    group: discord-github-utils
    url: "https://ghutils.object.gay/api/health"
    conditions:
      - "[STATUS] == 200"

  - name: discord-github-utils-docker
    <<: *docker
    group: discord-github-utils
    url: "${SOCKET_PROXY}/containers/discord-github-utils-bot-1/json"
  
  - name: hexbug-prod-docker
    <<: *docker
    group: hexbug
    url: "${SOCKET_PROXY}/containers/hexbug-bot-1/json"
  
  - name: hexbug-beta-docker
    <<: *docker
    group: hexbug
    url: "${SOCKET_PROXY}/containers/beta-hexbug-bot-1/json"

  - name: hexxy.media-api
    group: hexxy.media
    url: "https://hexxy.media/api/v0/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == OK"

  - name: hexxy.media-homepage
    group: hexxy.media
    url: https://hexxy.media
    conditions:
      - "[STATUS] == 200"

  - name: postgres
    group: internal
    url: "tcp://localhost:5432"
    conditions:
      - "[CONNECTED] == true"
    ui:
      hide-hostname: true

  - name: fragments-wiki
    group: misc
    url: "https://fragments.objectobject.ca/wiki"
    conditions:
      - "[STATUS] == 200"

  - name: object.gay-api
    group: object.gay
    url: "https://object.gay/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == OK"

  - name: object.gay-docker
    <<: *docker
    group: object.gay
    url: "${SOCKET_PROXY}/containers/object-gay-root-1/json"

  - name: object.gay-zipline
    group: object.gay
    url: "https://see.object.gay"
    conditions:
      - "[STATUS] == 200"
