# YAML anchors

_defaults:
  docker: &docker
    conditions:
      - "[STATUS] == 200"
      - "[BODY].State.Health.Status == healthy"
    ui:
      hide-hostname: true

# main config

storage:
  type: sqlite
  path: /data/data.db

ui:
  title: "Gatus @ status.objectobject.ca"
  header: "status.objectobject.ca"
  description: "Gatus page for services hosted on objectobject.ca."
  buttons:
    - name: Dozzle
      link: https://status.objectobject.ca/dozzle
    - name: Source
      link: https://github.com/object-Object/objectobject.ca

alerting:
  discord:
    default-alert:
      # deployments should be done within 5 minutes, hopefully
      failure-threshold: 5
      success-threshold: 3
      send-on-resolved: true

endpoints:
  - name: api
    group: discord-github-utils
    url: "https://ghutils.object.gay/api/health"
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: docker
    group: discord-github-utils
    <<: *docker
    url: "${SOCKET_PROXY}/containers/discord-github-utils-bot-1/json"
    alerts:
      - type: discord
  
  - name: prod-docker
    group: hexbug
    <<: *docker
    url: "${SOCKET_PROXY}/containers/hexbug-bot-1/json"
    alerts:
      - type: discord
  
  - name: beta-docker
    group: hexbug
    <<: *docker
    url: "${SOCKET_PROXY}/containers/beta-hexbug-bot-1/json"
    alerts:
      - type: discord

  - name: api
    group: hexxy.media
    url: "https://hexxy.media/api/v0/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == OK"
    alerts:
      - type: discord

  - name: postgres
    group: hexxy.media
    url: "https://hexxy.media/api/v0/pattern/number/0"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].pattern == aqaa"
    alerts:
      - type: discord

  - name: homepage
    group: hexxy.media
    url: https://hexxy.media
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: api
    group: object.gay
    url: "https://object.gay/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == OK"
    alerts:
      - type: discord

  - name: docker
    group: object.gay
    <<: *docker
    url: "${SOCKET_PROXY}/containers/object-gay-root-1/json"
    alerts:
      - type: discord

  - name: homepage
    group: object.gay
    url: "https://object.gay"
    conditions:
      - "[STATUS] == 200"
      # FIXME: hack
      - '[BODY] == pat(*<meta property="og:url" content="https://github.com/object-Object"*)'
    alerts:
      - type: discord

  - name: homepage-redirect
    group: object.gay
    url: "https://object.gay"
    client:
      ignore-redirect: true
    conditions:
      - "[STATUS] == 302"
    alerts:
      - type: discord

  - name: zipline
    group: object.gay
    url: "https://see.object.gay"
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: fragments-wiki
    group: objectobject.ca
    url: "https://fragments.objectobject.ca/wiki"
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: homepage
    group: objectobject.ca
    url: "https://objectobject.ca"
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord

  - name: homepage-http
    group: objectobject.ca
    url: "http://objectobject.ca"
    client:
      ignore-redirect: true
    conditions:
      - "[STATUS] == 302"
    alerts:
      - type: discord
