version: 0.0
os: linux 
files:
  - source: /
    destination: /var/lib/codedeploy-apps/objectobject-ca
  - source: alloy
    destination: /etc/alloy
permissions:
  - object: /etc/alloy
    pattern: "*.alloy"
    owner: root
    group: root
    mode: 644
    type:
      - file
  - object: /etc/alloy/secrets
    owner: root
    group: alloy
    mode: 640
    type:
      - file
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: hooks/application-stop.sh
      timeout: 60
  ApplicationStart:
    - location: hooks/application-start.sh
      timeout: 120
  ValidateService:
    - location: hooks/validate-service.sh
      timeout: 60
