name: Build and deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  STACK_NAME: prod-hexxy-media
  CDK_IAM_ROLE_ARN: arn:aws:iam::511603859520:role/prod-objectobject-ca-GitHubActionsCDKRole19D97701-sweSB0Sp33WN

jobs:
  deploy-aws-cdk:
    runs-on: ubuntu-latest
    environment:
      name: prod-aws-cdk
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.CDK_IAM_ROLE_ARN }}

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - name: Install Python packages
        run: pip install .[aws-cdk]
      
      - name: Deploy CDK stack
        run: cdk deploy prod --ci --require-approval never
