name: Build and deploy

on:
  push:
    branches: "main"
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  NODE_VERSION: 18

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    environment:
      name: prod-terraform
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: object-Object/ci/setup@v0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          python-packages: -e .
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v1
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          mode: auto-approve-apply
          stackName: prod
          terraformCloudToken: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  deploy-aws-cdk:
    runs-on: ubuntu-latest
    environment:
      name: prod-aws-cdk
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: object-Object/ci/setup@v0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          python-packages: -e .
          node-version: ${{ env.NODE_VERSION }}
          npm-packages: aws-cdk
          role-to-assume: default

      - name: Deploy CDK stack
        run: cdk deploy prod --ci --require-approval never --no-lookups
